# Generated by Django 6.0.6 on 2026-06-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoice_notes_payment_method_payment_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
