# Generated by Django 6.0.6 on 2026-06-21 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_session_is_cancelled_session_is_extra_and_more'),
        ('members', '0004_membernote'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='max_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_list', to='classes.class')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_list', to='members.member')),
            ],
            options={
                'ordering': ['joined_at'],
                'unique_together': {('assigned_class', 'member')},
            },
        ),
    ]
