# Generated by Django 6.0.6 on 2026-06-21 18:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('members', '0007_memberapplication_address_line1_and_more'),
        ('organisations', '0005_organisation_custom_css_organisation_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaiverTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='waiver_templates/')),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiver_templates', to='organisations.organisation')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SignedWaiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_pdf', models.FileField(upload_to='signed_waivers/%Y/%m/')),
                ('signer_name', models.CharField(max_length=255)),
                ('signed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('offline', models.BooleanField(default=False, help_text='Signed on paper, uploaded manually')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_waivers', to='members.memberapplication')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signed_waivers', to='members.member')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signed_copies', to='documents.waivertemplate')),
            ],
            options={
                'ordering': ['-signed_at'],
            },
        ),
    ]
