# Generated by Django 6.0.6 on 2026-06-21 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0002_member_emergency_contact_2_name_and_more'),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressionStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('colour', models.CharField(blank=True, help_text='Hex colour, e.g. #FF0000', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_default', models.BooleanField(default=False, help_text='New members are assigned this stage automatically when the system is set to auto-assign.')),
            ],
            options={
                'ordering': ['system', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MemberProgression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieved_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='members.member')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='progression.progressionstage')),
            ],
            options={
                'ordering': ['-achieved_date'],
            },
        ),
        migrations.CreateModel(
            name='ProgressionSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('assign_to_new_members', models.BooleanField(default=False, help_text='Automatically assign new members to the default stage in this system.')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progression_systems', to='organisations.organisation')),
            ],
            options={
                'ordering': ['organisation', 'order', 'name'],
                'unique_together': {('organisation', 'name')},
            },
        ),
        migrations.AddField(
            model_name='progressionstage',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='progression.progressionsystem'),
        ),
        migrations.AlterUniqueTogether(
            name='progressionstage',
            unique_together={('system', 'name')},
        ),
    ]
