# Generated by Django 6.0.6 on 2026-06-20 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressionStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progression_stages', to='organisations.organisation')),
            ],
            options={
                'ordering': ['organisation', 'order', 'name'],
                'unique_together': {('organisation', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MemberProgression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieved_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='members.member')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='progression.progressionstage')),
            ],
            options={
                'ordering': ['-achieved_date'],
            },
        ),
    ]
