# Generated by Django 6.0.6 on 2026-06-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progression', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressionstage',
            name='colour',
            field=models.CharField(blank=True, help_text='Hex colour, e.g. #FF0000', max_length=7),
        ),
    ]
