# Generated by Django 6.0.6 on 2026-06-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0004_organisationmember_coaching_licence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='custom_css',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
