# Generated by Django 6.0.6 on 2026-06-20 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='emergency_contact_2_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='emergency_contact_2_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
