# Generated by Django 6.0.6 on 2026-06-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_emergency_contact_2_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='monthly_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='subscription_status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
