# Generated by Django 6.0.6 on 2026-06-21 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_membernote'),
        ('organisations', '0003_organisation_phone_organisation_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('guardian_name', models.CharField(blank=True, max_length=255)),
                ('guardian_email', models.EmailField(blank=True, max_length=254)),
                ('guardian_phone', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Any additional information from the applicant')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='organisations.organisation')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
