# Generated by Django 6.0.6 on 2026-06-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_member_licence_expiry_member_licence_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberapplication',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='memberapplication',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='memberapplication',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='memberapplication',
            name='county',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='memberapplication',
            name='postcode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='memberapplication',
            name='signature_data',
            field=models.TextField(blank=True, help_text='Base64-encoded PNG of drawn signature'),
        ),
    ]
