# Generated by Django 6.0.6 on 2026-06-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_memberapplication_address_line1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='medical_info',
            field=models.TextField(blank=True, help_text='Medical conditions, allergies, or other health information coaches should know about'),
        ),
        migrations.AddField(
            model_name='memberapplication',
            name='medical_info',
            field=models.TextField(blank=True),
        ),
    ]
